"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import React, { useReducer } from "react";
import reducer from "@/components/groupsReducer";
const initialState = JSON.parse(localStorage.getItem("groups") || "[]");

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const GroupContext = React.createContext();

export default function RootLayout({ children }) {
  const [group, dispatch] = useReducer(reducer, initialState);

  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl m-auto my-8`}>
        <GroupContext.Provider value={{ group, dispatch }}>
          {children}
        </GroupContext.Provider>
      </body>
    </html>
  );
}
