"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import React, { useReducer } from "react";
import reducerGroups from "@/hooks/groupsReducer";
import reducerPosts from "@/hooks/postsReducer";

let initialStateGroups = "[]";
let initialStatePosts = "[]";

if (typeof window !== "undefined") {
  initialStateGroups = JSON.parse(localStorage.getItem("groups") || "[]");
  initialStatePosts = JSON.parse(localStorage.getItem("groups") || "[]");
}

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const GroupContext = React.createContext();
export const PostsContext = React.createContext();

export default function RootLayout({ children }) {
  const [group, dispatchG] = useReducer(reducerGroups, initialStateGroups);
  const [posts, dispatchP] = useReducer(reducerPosts, initialStatePosts);

  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl m-auto my-8`}>
        <GroupContext.Provider value={{ group, dispatch: dispatchG }}>
          <PostsContext.Provider value={{ posts, dispatch: dispatchP }}>
            {children}
          </PostsContext.Provider>
        </GroupContext.Provider>
      </body>
    </html>
  );
}
